"""Unit tests for pipeline.allowed_modifications.render_allowed_modifications."""

from pipeline.allowed_modifications import render_allowed_modifications


def test_empty_input_returns_empty_string() -> None:
    assert render_allowed_modifications("") == ""
    assert render_allowed_modifications([]) == ""
    assert render_allowed_modifications(None) == ""


def test_non_empty_renders_header_preamble_and_entries() -> None:
    entries = [
        "package-lock.json — derived from package.json",
        "tests/golden/*.snap — golden snapshots regenerated by tests",
    ]

    out = render_allowed_modifications(entries)

    assert out.startswith("## Allowed Companion Modifications")
    # Code-owned semantics preamble: allowance is scope-only, content is
    # still reviewed, out-of-list diff is still a scope violation.
    assert "NOT a scope violation" in out
    assert "Review the CONTENT" in out
    assert "still a scope violation and must be rejected" in out
    # Every entry appears verbatim as a bullet.
    for entry in entries:
        assert f"- {entry}" in out


def test_entries_are_not_modified() -> None:
    entries = [
        "  spaced.lock — keep surrounding spaces  ",
        "no-reason-dash-entry",
    ]

    out = render_allowed_modifications(entries)

    assert "-   spaced.lock — keep surrounding spaces  " in out
    assert "- no-reason-dash-entry" in out
    # The renderer must not parse or normalise the "glob — reason" shape.
    assert entries == [
        "  spaced.lock — keep surrounding spaces  ",
        "no-reason-dash-entry",
    ]
