"""pipeline.evidence.bundle — Run evidence bundle writer.

Two entry points:

* :func:`write_placeholder` — REA-0 stub. Used early in run lifecycle
  before the collector has enough state to produce a full bundle.
  Schema version stays ``"0-placeholder"``.
* :func:`write_bundle` — REA-3. Reads the run dir via
  :func:`pipeline.evidence.collector.collect_evidence`, validates
  against the v1 schema, writes ``evidence.json`` and ``evidence.md``.

Run finalize calls :func:`write_bundle` once everything else
(``meta.json``, ``events.jsonl``, ``metrics.json``) has landed. CLI
``orcho evidence <run_id>`` rebuilds the bundle on demand from the
same run dir; the file content matches what the run wrote at
finalize unless the operator regenerated by hand.
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

from pipeline.evidence.collector import collect_evidence
from pipeline.evidence.render_md import render_evidence_md
from pipeline.evidence.schema import (
    EVIDENCE_SCHEMA_VERSION,
    EvidenceSchemaError,
    validate_bundle,
)

#: File name written into the run dir. Locked: REA-3 keeps this name
#: across schema versions; consumers route on the JSON ``schema_version``.
EVIDENCE_FILE_NAME: Final[str] = "evidence.json"

#: Markdown sidecar.
EVIDENCE_MD_FILE_NAME: Final[str] = "evidence.md"

#: Placeholder schema version emitted by REA-0 stub.
EVIDENCE_SCHEMA_VERSION_PLACEHOLDER: Final[str] = "0-placeholder"


def write_placeholder(
    run_dir: Path | str,
    *,
    run_id: str,
    status: str,
) -> Path:
    """Write the REA-0 placeholder ``evidence.json``.

    Used when the run halts before the collector can compose a full
    bundle, or as the early-stage stub that locks the file path. The
    payload carries ``schema_version="0-placeholder"`` so consumers
    can detect the stub vs the v1 bundle.
    """
    target = Path(run_dir)
    target.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": EVIDENCE_SCHEMA_VERSION_PLACEHOLDER,
        "run_id": run_id,
        "run_dir": str(target),
        "status": status,
        "created_at": datetime.now(UTC).isoformat(timespec="seconds"),
    }
    out = target / EVIDENCE_FILE_NAME
    out.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    _emit_artifact_event(out)
    return out


def write_bundle(run_dir: Path | str) -> tuple[Path, Path]:
    """Compose the v1 evidence bundle and write it next to the run dir.

    Args:
        run_dir: canonical run dir (contains ``meta.json`` /
            ``events.jsonl`` / ``metrics.json``).

    Returns:
        ``(json_path, md_path)`` — the two files written.

    Raises:
        :class:`pipeline.evidence.schema.EvidenceSchemaError` if the
        composed bundle fails its own contract (caught by callers
        that prefer to fall back to the placeholder).
    """
    target = Path(run_dir)
    bundle = collect_evidence(target)
    validate_bundle(bundle)

    json_path = target / EVIDENCE_FILE_NAME
    md_path = target / EVIDENCE_MD_FILE_NAME

    json_path.write_text(
        json.dumps(bundle, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    md_path.write_text(render_evidence_md(bundle), encoding="utf-8")

    _emit_artifact_event(json_path)
    _emit_artifact_event(md_path)
    return json_path, md_path


def write_bundle_or_placeholder(
    run_dir: Path | str, *, run_id: str, status: str,
) -> Path:
    """Best-effort bundle writer for run finalize.

    Tries the full v1 composition first. Falls back to the REA-0
    placeholder when collection fails (missing files / partial run /
    schema mismatch) so the run dir always carries an
    ``evidence.json`` after finalize. Returns the JSON path.
    """
    try:
        json_path, _ = write_bundle(run_dir)
        return json_path
    except (EvidenceSchemaError, FileNotFoundError, OSError, ValueError):
        return write_placeholder(run_dir, run_id=run_id, status=status)


# ── Internals ──────────────────────────────────────────────────────────────


def _emit_artifact_event(path: Path) -> None:
    """Best-effort ``artifact.created`` emission.

    Telemetry failure must never raise out of the bundle writer; the
    bundle is the source of truth and a missed event is recoverable.
    """
    try:
        from core.observability import events as _events
        kind = (
            "evidence_md" if path.name.endswith(".md") else "evidence"
        )
        _events.emit(
            "artifact.created",
            path=str(path),
            artifact_kind=kind,
            size_bytes=path.stat().st_size,
        )
    except Exception:
        pass


# ── Public re-exports for backwards compat with REA-0 callers ──────────────

__all__ = [
    "EVIDENCE_FILE_NAME",
    "EVIDENCE_MD_FILE_NAME",
    "EVIDENCE_SCHEMA_VERSION_PLACEHOLDER",
    "EVIDENCE_SCHEMA_VERSION",
    "write_bundle",
    "write_bundle_or_placeholder",
    "write_placeholder",
]
