"""pipeline.control — operator-facing control surfaces (decisions, overrides).

Initial scope: parsing/normalising operator decision overrides delivered
via the ``--decision`` / ``--decision-feedback`` CLI flags, and resume-
intent classification consumed by every frontend that exposes ``--resume``.
"""
from __future__ import annotations

from pipeline.control.continuation import (
    ContinuationDecision,
    ContinuationRequest,
    ContinuationResolution,
    resolve_continuation,
    resolve_continuation_decision,
)
from pipeline.control.handoff_banners import (
    RetryOutcome,
    print_retry_feedback_banner,
    print_retry_outcome_banner,
    render_retry_feedback_banner,
    render_retry_outcome_banner,
    sanitize_feedback_preview,
)
from pipeline.control.handoff_decisions import (
    HandoffDecisionAction,
    HandoffDecisionContext,
    HandoffDecisionResult,
    load_handoff_decision,
)
from pipeline.control.handoff_labels import (
    human_directed_flag_from_state,
    is_human_directed_round,
    render_round_label,
)
from pipeline.control.implement_handoff_digest import (
    ImplementIncompleteDigest,
    classify_implement_incomplete,
    render_implement_incomplete_digest,
)
from pipeline.control.operator_decisions import (
    DECISION_TARGETS_BY_SUBCOMMAND,
    OperatorDecisionError,
    OperatorDecisionOverride,
    parse_operator_decisions,
)
from pipeline.control.resume_context import (
    ActiveFollowupChild,
    CheckpointFollowupLineage,
    FollowupResumeFields,
    LatestRunNotFound,
    ResolvedResumeContext,
    ResumeContextError,
    ResumedMeta,
    ResumeIntentOptions,
    ResumeMode,
    build_checkpoint_followup_lineage,
    build_followup_resume_fields,
    classify_resume_mode,
    detect_active_followup_child,
    extract_cross_followup_session_seeds,
    extract_followup_session_seeds,
    get_resume_intent_options,
    is_terminal_commit_decision_fix,
    is_terminal_commit_delivery_pending,
    is_terminal_commit_delivery_scope_blocked,
    is_terminal_final_acceptance_rejected,
    is_terminal_phase_handoff_halt,
    is_terminal_success,
    load_resume_meta,
    meta_run_kind,
    resolve_latest_run,
    resolve_project,
    resolve_projects_argv,
    resolve_resume_profile,
    resolve_task,
)
from pipeline.control.resume_preflight import (
    ActiveHandoffPreflight,
    build_signal_from_active_payload,
    detect_active_handoff_without_decision,
    render_noninteractive_hint,
    resolve_active_handoff_interactively,
)
from pipeline.control.resume_prompt import (
    PromptedResumeIntent,
    prompt_resume_intent,
    should_prompt_for_resume_intent,
)
from pipeline.control.reviewed_loop import (
    ReviewedLoopPolicy,
    ReviewedLoopResult,
    ReviewedLoopStatus,
    ReviewedRound,
    ReviewOutcome,
    run_reviewed_loop,
)

__all__ = [
    "ActiveFollowupChild",
    "ActiveHandoffPreflight",
    "CheckpointFollowupLineage",
    "DECISION_TARGETS_BY_SUBCOMMAND",
    "FollowupResumeFields",
    "HandoffDecisionAction",
    "HandoffDecisionContext",
    "HandoffDecisionResult",
    "ImplementIncompleteDigest",
    "LatestRunNotFound",
    "OperatorDecisionError",
    "OperatorDecisionOverride",
    "PromptedResumeIntent",
    "ResolvedResumeContext",
    "ResumeContextError",
    "ResumeIntentOptions",
    "ResumeMode",
    "ResumedMeta",
    "RetryOutcome",
    "ReviewOutcome",
    "ReviewedLoopPolicy",
    "ReviewedLoopResult",
    "ReviewedLoopStatus",
    "ReviewedRound",
    "build_checkpoint_followup_lineage",
    "build_followup_resume_fields",
    "build_signal_from_active_payload",
    "classify_implement_incomplete",
    "classify_resume_mode",
    "ContinuationDecision",
    "ContinuationRequest",
    "ContinuationResolution",
    "resolve_continuation",
    "detect_active_followup_child",
    "detect_active_handoff_without_decision",
    "extract_cross_followup_session_seeds",
    "extract_followup_session_seeds",
    "get_resume_intent_options",
    "human_directed_flag_from_state",
    "is_human_directed_round",
    "is_terminal_commit_decision_fix",
    "is_terminal_commit_delivery_pending",
    "is_terminal_commit_delivery_scope_blocked",
    "is_terminal_final_acceptance_rejected",
    "is_terminal_phase_handoff_halt",
    "is_terminal_success",
    "load_handoff_decision",
    "load_resume_meta",
    "meta_run_kind",
    "parse_operator_decisions",
    "print_retry_feedback_banner",
    "print_retry_outcome_banner",
    "prompt_resume_intent",
    "render_implement_incomplete_digest",
    "render_noninteractive_hint",
    "render_retry_feedback_banner",
    "render_retry_outcome_banner",
    "render_round_label",
    "resolve_active_handoff_interactively",
    "resolve_continuation_decision",
    "resolve_latest_run",
    "resolve_project",
    "resolve_projects_argv",
    "resolve_resume_profile",
    "resolve_task",
    "run_reviewed_loop",
    "sanitize_feedback_preview",
    "should_prompt_for_resume_intent",
]
